//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginMotelUser.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BILL()
        {
            this.PARTICURSERVICEs = new HashSet<PARTICURSERVICE>();
        }
    
        public int idBill { get; set; }
        public Nullable<int> idRoom { get; set; }
        public string idStaff { get; set; }
        public Nullable<decimal> Total { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<bool> Paid { get; set; }
    
        public virtual MOTELROOM MOTELROOM { get; set; }
        public virtual STAFF STAFF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTICURSERVICE> PARTICURSERVICEs { get; set; }
    }
}
