//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginMotelUser.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOTELROOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOTELROOM()
        {
            this.BILLs = new HashSet<BILL>();
            this.RENTINFOes = new HashSet<RENTINFO>();
        }
    
        public int idRoom { get; set; }
        public string roomName { get; set; }
        public Nullable<bool> State { get; set; }
        public Nullable<int> idRoomRank { get; set; }
        public string Range { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILLs { get; set; }
        public virtual ROMERANK ROMERANK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RENTINFO> RENTINFOes { get; set; }
    }
}
