//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginMotelUser.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICURSERVICE
    {
        public int idBill { get; set; }
        public Nullable<int> oldIndex { get; set; }
        public Nullable<int> newIndex { get; set; }
        public Nullable<decimal> Total { get; set; }
        public int idService { get; set; }
    
        public virtual BILL BILL { get; set; }
        public virtual SERVIECE SERVIECE { get; set; }
    }
}
