//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginMotelUser.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RENTINFO
    {
        public string idCarCus { get; set; }
        public int idRoom { get; set; }
        public Nullable<System.DateTime> checkInDate { get; set; }
        public Nullable<System.DateTime> checkOutDate { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual MOTELROOM MOTELROOM { get; set; }
    }
}
