//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginMotelUser.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROMERANK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROMERANK()
        {
            this.MOTELROOMs = new HashSet<MOTELROOM>();
        }
    
        public int idRomRank { get; set; }
        public string Rank { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string About { get; set; }
        public Nullable<decimal> Deposits { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOTELROOM> MOTELROOMs { get; set; }
    }
}
